version: '3'
services:
    app:
        restart: always
        build: .
        command: bash -c "python3 manage.py collectstatic --noinput
                          & python3 manage.py runserver 0.0.0.0:8000"
        ports:
          - "8000:8000"
        networks:
          - test
        env_file:
          - variables.env
        depends_on:
          - postgres
          - mongo
        volumes:
          - ./:/library
          - ./static:/library/static

    mongo:
        image: mongo:4.2-bionic
        restart: always
        volumes:
            - ./mongo_db/:/data/db
        networks:
            - test

    postgres:
        image: postgres:11.5
        restart: always
        volumes:
            - ./postgres_db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - variables.env
        networks:
            - test

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./uploads:/uploads
            - ./static:/static
        networks:
            - test
        depends_on:
          - app

networks:
    test:
