version: '3'
services:
  app:
    image: 276444395597.dkr.ecr.eu-central-1.amazonaws.com/library_app
    build:
      dockerfile: ./Dockerfile
      context: .
    command: ./run.sh

  nginx:
    image: 276444395597.dkr.ecr.eu-central-1.amazonaws.com/library_nginx
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    ports:
    - "80:80"

#  mongo:
#    image: mongo:4.2-bionic
#    restart: always
#    volumes:
#      - ./mongo_db/:/data/db
#    networks:
#      - library
#    ports:
#      - "27017:27017"
#
#  postgres:
#    image: postgres:11.5
#    restart: always
#    volumes:
#      - ./postgres_db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    env_file:
#      - variables.env
#    networks:
#      - library
