# Generated by Django 2.2.5 on 2019-09-18 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('author', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=None, null=True), size=None)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
