# Generated by Django 2.2.5 on 2019-09-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
